spring:
   profiles:
      active: dev-6610
      
---
server:
   port: 6610 # 指定Eureka服务器端口

spring:
   profiles: dev-6610
   application:
      name: eureka-server # 服务名
      
eureka:
   instance:
      hostname: 127.0.0.1
   client:
      register-with-eureka: false
      fetch-registry: false
      service-url:
         defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
   